
import FormField = require('dw/web/FormField')
import FormGroup = require('dw/web/FormGroup');
import FormList = require('dw/web/FormList');
import FormAction = require('dw/web/FormAction');
// autogeneratedfile

/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#2)*/
declare class FormCreditCard extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#5) */
	editNumber : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#12) */
	paymentMethod : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#14) */
	cardType : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#17) */
	cardNumber : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#20) */
	cardOwner : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#23) */
	expirationMonth : FormField<number>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#42) */
	expirationYear : FormField<number>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#49) */
	securityCode : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#52) */
	saveCard : FormField<boolean>
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\states.xml#2)*/
declare class FormStates extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\states.xml#3) */
	stateCode : FormField<string>
}
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#2)*/
declare class FormShippingShippingAddress extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#12) */
	addressFields : FormAddress
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#15) */
	shippingMethodID : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#18) */
	shippingAddressUseAsBillingAddress : FormField<boolean>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#20) */
	isGift : FormField<boolean>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#21) */
	giftMessage : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#24) */
	save : FormAction
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#2)*/
declare class FormShipping extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#4) */
	shipmentUUID : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#6) */
	productLineItemUUID : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#9) */
	shippingAddress : FormShippingShippingAddress
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\newPasswords.xml#2)*/
declare class FormNewPasswords extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\newPasswords.xml#3) */
	newpassword : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\newPasswords.xml#13) */
	newpasswordconfirm : FormField<string>
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\coRegisteredCustomer.xml#2)*/
declare class FormCoRegisteredCustomer extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\coRegisteredCustomer.xml#4) */
	email : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\coRegisteredCustomer.xml#16) */
	password : FormField<string>
}
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#2)*/
declare class FormProfileCustomer extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#4) */
	firstname : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#13) */
	lastname : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#22) */
	email : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#35) */
	emailconfirm : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#48) */
	phone : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#57) */
	addtoemaillist : FormField<boolean>
}
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#2)*/
declare class FormProfileLogin extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#64) */
	password : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#75) */
	passwordconfirm : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#86) */
	currentpassword : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#96) */
	newpasswords : FormNewPasswords
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#2)*/
declare class FormProfile extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#3) */
	customer : FormProfileCustomer
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#63) */
	login : FormProfileLogin
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\contactInfo.xml#2)*/
declare class FormContactInfo extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\contactInfo.xml#5) */
	phone : FormField<string>
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\coCustomer.xml#2)*/
declare class FormCoCustomer extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\coCustomer.xml#4) */
	email : FormField<string>
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\billing.xml#2)*/
declare class FormBilling extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\billing.xml#4) */
	shippingAddressUseAsBillingAddress : FormField<boolean>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\billing.xml#7) */
	addressFields : FormAddress
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\billing.xml#9) */
	contactInfoFields : FormContactInfo
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\billing.xml#11) */
	paymentMethod : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\billing.xml#13) */
	creditCardFields : FormCreditCard
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\billing.xml#15) */
	subscribe : FormField<boolean>
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#2)*/
declare class FormAddress extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#4) */
	addressId : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#6) */
	firstName : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#8) */
	lastName : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#10) */
	address1 : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#12) */
	address2 : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#14) */
	city : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#18) */
	postalCode : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#26) */
	country : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#34) */
	states : FormStates
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#37) */
	phone : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#44) */
	apply : FormAction
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#45) */
	remove : FormAction
}
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#2)*/
declare class FormGiftRegistryGiftRegistryEvent extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#5) */
	event : FormGiftRegistryEvent
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#6) */
	registrant : FormGiftRegistryRegistrant
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#7) */
	coRegistrant : FormGiftRegistryRegistrant
}
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#2)*/
declare class FormGiftRegistryGiftRegistryShippingAddress extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#12) */
	preEventShippingAddress : FormAddress
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#13) */
	postEventShippingAddress : FormAddress
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#2)*/
declare class FormGiftRegistry extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#4) */
	giftRegistryEvent : FormGiftRegistryGiftRegistryEvent
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#11) */
	giftRegistryShippingAddress : FormGiftRegistryGiftRegistryShippingAddress
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#16) */
	coRegistrantCheck : FormField<boolean>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#20) */
	postShippingCheck : FormField<boolean>
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryEvent.xml#2)*/
declare class FormGiftRegistryEvent extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryEvent.xml#3) */
	eventName : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryEvent.xml#7) */
	eventDate : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryEvent.xml#13) */
	eventCountry : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryEvent.xml#20) */
	eventState : FormStates
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryEvent.xml#24) */
	eventCity : FormField<string>
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryRegistrant.xml#2)*/
declare class FormGiftRegistryRegistrant extends FormGroup {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryRegistrant.xml#3) */
	role : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryRegistrant.xml#8) */
	firstName : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryRegistrant.xml#13) */
	lastName : FormField<string>
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryRegistrant.xml#18) */
	email : FormField<string>
}

declare global {
interface SFCCForms {
	creditCard: FormCreditCard
	states: FormStates
	shipping: FormShipping
	newPasswords: FormNewPasswords
	coRegisteredCustomer: FormCoRegisteredCustomer
	profile: FormProfile
	contactInfo: FormContactInfo
	coCustomer: FormCoCustomer
	billing: FormBilling
	address: FormAddress
	giftRegistry: FormGiftRegistry
	giftRegistryEvent: FormGiftRegistryEvent
	giftRegistryRegistrant: FormGiftRegistryRegistrant
}
}


/****** SRFA *******/

interface SfraAction {
    description: string | null;
    label: string | null;
    submitted: boolean | null;
    triggered: boolean | null;
    formType: string;
}

interface SfraFiledOptions {
	checked: boolean,
	htmlValue: string,
	label: string,
	id: string,
	selected: boolean,
	value: string
}

interface SfraFieldBoolean {
	checked: boolean;
	selected: boolean;
}

interface SfraFieldString {
	maxLength: number;
	minLength: number;
	regEx: string
}

interface SfraFieldInteger {
	maxValue: number;
	minValue: number;
}

interface SfraField<T> {
	valid: boolean;
	error: string | null
	readonly attributes: string;
	value: T;
	options: SfraFiledOptions[];
	selectedOption: string;
	formType: string;

	htmlValue: string,
	mandatory: boolean,
	dynamicHtmlName: string
	htmlName: string
}

interface SfraFormBase<T> {
	clear() : void;
	copyFrom(src: object): void;
	toObject(): any;
	valid: boolean;
	base: T
	htmlName: string,
	dynamicHtmlName: string,
	error: string | null,
	attributes: string,
	formType: 'formGroup'
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#2)*/
interface SfraFormCreditCard extends SfraFormBase<FormCreditCard> {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#5) */
	editNumber : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#12) */
	paymentMethod : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#14) */
	cardType : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#17) */
	cardNumber : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#20) */
	cardOwner : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#23) */
	expirationMonth : SfraField<number> & SfraFieldInteger
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#42) */
	expirationYear : SfraField<number> & SfraFieldInteger
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#49) */
	securityCode : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\creditCard.xml#52) */
	saveCard : SfraField<boolean> & SfraFieldBoolean
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\states.xml#2)*/
interface SfraFormStates extends SfraFormBase<FormStates> {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\states.xml#3) */
	stateCode : SfraField<string> & SfraFieldString
}
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#2)*/
interface SfraFormShippingShippingAddress {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#12) */
	addressFields : SfraFormAddress
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#15) */
	shippingMethodID : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#18) */
	shippingAddressUseAsBillingAddress : SfraField<boolean> & SfraFieldBoolean
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#20) */
	isGift : SfraField<boolean> & SfraFieldBoolean
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#21) */
	giftMessage : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#24) */
	save : SfraAction
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#2)*/
interface SfraFormShipping extends SfraFormBase<FormShipping> {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#4) */
	shipmentUUID : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#6) */
	productLineItemUUID : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\shipping.xml#9) */
	shippingAddress : SfraFormShippingShippingAddress
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\newPasswords.xml#2)*/
interface SfraFormNewPasswords extends SfraFormBase<FormNewPasswords> {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\newPasswords.xml#3) */
	newpassword : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\newPasswords.xml#13) */
	newpasswordconfirm : SfraField<string> & SfraFieldString
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\coRegisteredCustomer.xml#2)*/
interface SfraFormCoRegisteredCustomer extends SfraFormBase<FormCoRegisteredCustomer> {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\coRegisteredCustomer.xml#4) */
	email : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\coRegisteredCustomer.xml#16) */
	password : SfraField<string> & SfraFieldString
}
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#2)*/
interface SfraFormProfileCustomer {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#4) */
	firstname : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#13) */
	lastname : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#22) */
	email : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#35) */
	emailconfirm : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#48) */
	phone : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#57) */
	addtoemaillist : SfraField<boolean> & SfraFieldBoolean
}
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#2)*/
interface SfraFormProfileLogin {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#64) */
	password : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#75) */
	passwordconfirm : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#86) */
	currentpassword : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#96) */
	newpasswords : SfraFormNewPasswords
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#2)*/
interface SfraFormProfile extends SfraFormBase<FormProfile> {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#3) */
	customer : SfraFormProfileCustomer
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\profile.xml#63) */
	login : SfraFormProfileLogin
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\contactInfo.xml#2)*/
interface SfraFormContactInfo extends SfraFormBase<FormContactInfo> {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\contactInfo.xml#5) */
	phone : SfraField<string> & SfraFieldString
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\coCustomer.xml#2)*/
interface SfraFormCoCustomer extends SfraFormBase<FormCoCustomer> {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\coCustomer.xml#4) */
	email : SfraField<string> & SfraFieldString
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\billing.xml#2)*/
interface SfraFormBilling extends SfraFormBase<FormBilling> {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\billing.xml#4) */
	shippingAddressUseAsBillingAddress : SfraField<boolean> & SfraFieldBoolean
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\billing.xml#7) */
	addressFields : SfraFormAddress
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\billing.xml#9) */
	contactInfoFields : SfraFormContactInfo
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\billing.xml#11) */
	paymentMethod : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\billing.xml#13) */
	creditCardFields : SfraFormCreditCard
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\billing.xml#15) */
	subscribe : SfraField<boolean> & SfraFieldBoolean
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#2)*/
interface SfraFormAddress extends SfraFormBase<FormAddress> {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#4) */
	addressId : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#6) */
	firstName : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#8) */
	lastName : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#10) */
	address1 : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#12) */
	address2 : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#14) */
	city : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#18) */
	postalCode : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#26) */
	country : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#34) */
	states : SfraFormStates
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#37) */
	phone : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#44) */
	apply : SfraAction
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\storefront-reference-architecture\cartridges\app_storefront_base\cartridge\forms\default\address.xml#45) */
	remove : SfraAction
}
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#2)*/
interface SfraFormGiftRegistryGiftRegistryEvent {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#5) */
	event : SfraFormGiftRegistryEvent
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#6) */
	registrant : SfraFormGiftRegistryRegistrant
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#7) */
	coRegistrant : SfraFormGiftRegistryRegistrant
}
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#2)*/
interface SfraFormGiftRegistryGiftRegistryShippingAddress {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#12) */
	preEventShippingAddress : SfraFormAddress
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#13) */
	postEventShippingAddress : SfraFormAddress
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#2)*/
interface SfraFormGiftRegistry extends SfraFormBase<FormGiftRegistry> {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#4) */
	giftRegistryEvent : SfraFormGiftRegistryGiftRegistryEvent
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#11) */
	giftRegistryShippingAddress : SfraFormGiftRegistryGiftRegistryShippingAddress
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#16) */
	coRegistrantCheck : SfraField<boolean> & SfraFieldBoolean
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistry.xml#20) */
	postShippingCheck : SfraField<boolean> & SfraFieldBoolean
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryEvent.xml#2)*/
interface SfraFormGiftRegistryEvent extends SfraFormBase<FormGiftRegistryEvent> {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryEvent.xml#3) */
	eventName : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryEvent.xml#7) */
	eventDate : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryEvent.xml#13) */
	eventCountry : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryEvent.xml#20) */
	eventState : SfraFormStates
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryEvent.xml#24) */
	eventCity : SfraField<string> & SfraFieldString
}
/** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryRegistrant.xml#2)*/
interface SfraFormGiftRegistryRegistrant extends SfraFormBase<FormGiftRegistryRegistrant> {
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryRegistrant.xml#3) */
	role : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryRegistrant.xml#8) */
	firstName : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryRegistrant.xml#13) */
	lastName : SfraField<string> & SfraFieldString
	 /** @source [definition](file:c:\WORK\Projects\Fenomax\dependencies\plugin_giftregistry\cartridges\plugin_giftregistry\cartridge\forms\default\giftRegistryRegistrant.xml#18) */
	email : SfraField<string> & SfraFieldString
}

declare global {
interface SFRAServerForms {
	getForm(name: 'creditCard'): SfraFormCreditCard
	getForm(name: 'states'): SfraFormStates
	getForm(name: 'shipping'): SfraFormShipping
	getForm(name: 'newPasswords'): SfraFormNewPasswords
	getForm(name: 'coRegisteredCustomer'): SfraFormCoRegisteredCustomer
	getForm(name: 'profile'): SfraFormProfile
	getForm(name: 'contactInfo'): SfraFormContactInfo
	getForm(name: 'coCustomer'): SfraFormCoCustomer
	getForm(name: 'billing'): SfraFormBilling
	getForm(name: 'address'): SfraFormAddress
	getForm(name: 'giftRegistry'): SfraFormGiftRegistry
	getForm(name: 'giftRegistryEvent'): SfraFormGiftRegistryEvent
	getForm(name: 'giftRegistryRegistrant'): SfraFormGiftRegistryRegistrant
}
}

declare global {
interface SRFAForms {
	creditCard: SfraFormCreditCard
	states: SfraFormStates
	shipping: SfraFormShipping
	newPasswords: SfraFormNewPasswords
	coRegisteredCustomer: SfraFormCoRegisteredCustomer
	profile: SfraFormProfile
	contactInfo: SfraFormContactInfo
	coCustomer: SfraFormCoCustomer
	billing: SfraFormBilling
	address: SfraFormAddress
	giftRegistry: SfraFormGiftRegistry
	giftRegistryEvent: SfraFormGiftRegistryEvent
	giftRegistryRegistrant: SfraFormGiftRegistryRegistrant
}
}